### ISSUE TITLE
.build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer

### ISSUE THREAD

**Issue by youngxiao** [lwplw/caffe_yolov2#1]
@lwplw  Hi, when build this repository, error ocurrs "caffe::ReorgLayer".  I have built `official caffe` and `other versions of caffe`, everything goes ok. In this repository, `ReorgLayer` for yolov2 has been added to caffe. So could you help me to solve this issue? Details:
```
CXX/LD -o .build_debug/tools/upgrade_solver_proto_text.bin
.build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<float>::Backward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<double>::Forward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<double>::Backward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<double>::Forward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<double>::Backward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<float>::Backward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
.build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
collect2: error: ld returned 1 exit status
Makefile:620: recipe for target '.build_debug/tools/upgrade_solver_proto_text.bin' failed
make: *** [.build_debug/tools/upgrade_solver_proto_text.bin] Error 1
```

**Comment by lwplw** [comment]
> @lwplw Hi, when build this repository, error ocurrs "caffe::ReorgLayer". I have built `official caffe` and `other versions of caffe`, everything goes ok. In this repository, `ReorgLayer` for yolov2 has been added to caffe. So could you help me to solve this issue? Details:
> 
> ```
> CXX/LD -o .build_debug/tools/upgrade_solver_proto_text.bin
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<float>::Backward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<double>::Forward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<double>::Backward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<double>::Forward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<double>::Backward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<float>::Backward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::RegionLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
> .build_debug/lib/libcaffe.so: undefined reference to `caffe::ReorgLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)'
> collect2: error: ld returned 1 exit status
> Makefile:620: recipe for target '.build_debug/tools/upgrade_solver_proto_text.bin' failed
> make: *** [.build_debug/tools/upgrade_solver_proto_text.bin] Error 1
> ```

hi,I re-downloaded this repo, compiled and passed, no problem.

> ```
> AR -o .build_debug/lib/libcaffe.a
> LD -o .build_debug/lib/libcaffe.so.1.0.0-rc3
> CXX/LD -o .build_debug/tools/compute_image_mean.bin
> CXX/LD -o .build_debug/tools/train_net.bin
> CXX/LD -o .build_debug/tools/caffe.bin
> CXX/LD -o .build_debug/tools/test_net.bin
> CXX/LD -o .build_debug/tools/finetune_net.bin
> CXX/LD -o .build_debug/tools/device_query.bin
> CXX/LD -o .build_debug/tools/convert_imageset.bin
> CXX/LD -o .build_debug/tools/upgrade_net_proto_text.bin
> CXX/LD -o .build_debug/tools/net_speed_benchmark.bin
> CXX/LD -o .build_debug/tools/upgrade_net_proto_binary.bin
> CXX/LD -o .build_debug/tools/upgrade_solver_proto_text.bin
> CXX/LD -o .build_debug/tools/extract_features.bin
> CXX/LD -o .build_debug/examples/mnist/convert_mnist_data.bin
> CXX/LD -o .build_debug/examples/cifar10/convert_cifar_data.bin
> CXX/LD -o .build_debug/examples/siamese/convert_mnist_siamese_data.bin
> CXX/LD -o .build_debug/examples/cpp_classification/classification.bin
> lwp@beedn:~/beednprojects/caffe_yolov2$ 
> ```

**Comment by youngxiao** [comment]
@lwplw Thanks a lot. It's ok now. 是我自己把 Makefile.config 改错. 现在编译通过. And I test my model both in caffe and darknet. There are differences between the results just as you said.  So should I add `padding=2` to the last `max pool` and train again? I modified .cfg file but it didn't start to train. 
I used the very old version of darknet. I tried in the latest version, it's ok now.

**Comment by youngxiao** [comment]
@lwplw Hi, I could train in darknet with the last max pool layer `padding=2`. When I used `darknet2caffe.py`  to trans the saved .weights to caffemodel. Some error ocurred. I guess the number of pameters in weights is not enough for some layer after modify `padding=2` in .cfg file.
Details:
```
 I1116 18:09:24.534112 10749 net.cpp:283] Network initialization done.
Traceback (most recent call last):
  File "darknet2caffe.py", line 411, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 61, in darknet2caffe
    start = load_conv2caffe(buf, start, params[conv_layer_name])
  File "darknet2caffe.py", line 98, in load_conv2caffe
    conv_param[0].data[...] = np.reshape(buf[start:start+weight.size], weight.shape); start = start + weight.size
  File "/home/xxx/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/xxx/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 23039 into shape (45,512,1,1)
```

**Comment by lwplw** [comment]
> @lwplw Hi, I could train in darknet with the last max pool layer `padding=2`. When I used `darknet2caffe.py` to trans the saved .weights to caffemodel. Some error ocurred. I guess the number of pameters in weights is not enough for some layer after modify `padding=2` in .cfg file.
> Details:
> 
> ```
>  I1116 18:09:24.534112 10749 net.cpp:283] Network initialization done.
> Traceback (most recent call last):
>   File "darknet2caffe.py", line 411, in <module>
>     darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
>   File "darknet2caffe.py", line 61, in darknet2caffe
>     start = load_conv2caffe(buf, start, params[conv_layer_name])
>   File "darknet2caffe.py", line 98, in load_conv2caffe
>     conv_param[0].data[...] = np.reshape(buf[start:start+weight.size], weight.shape); start = start + weight.size
>   File "/home/xxx/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>   File "/home/xxx/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
>     return getattr(obj, method)(*args, **kwds)
> ValueError: cannot reshape array of size 23039 into shape (45,512,1,1)
> ```

The calculation of the feature size of the conv and pool layers in darknet and caffe is different. You can see the source code in detail, and the pad layer and padding in the darknet are also different.

**Comment by youngxiao** [comment]
@lwplw Thanks. I have solved the problem.

**Comment by lwplw** [comment]
> @lwplw Thanks. I have solved the problem.

Great！
